name: "Sync With Organization"
# Run the workflow on push events to the main branch
# and pull requests merged into the main branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  git-sync:
    if: ${{ github.repository == 'https://github.com/vronnn/mindspace' }}
    runs-on: ubuntu-latest
    steps:
      - name: 🔒 Cencel Prev Workflow
        uses: styfle/cancel-workflow-action
      - name: 🔗 Synchronize Repository
        uses: wei/git-sync@v3
        with:
          source_repo: "https://vronnn:${{ secrets.ACCESS_TOKEN }}@github.com/vronnn/mindspace.git"
          source_branch: "main"
          destination_repo: "https://vronnn:${{ secrets.ACCESS_TOKEN }}@github.com/MindsSpace/mindspace-mobile.git"
          destination_branch: "main"
